version: "3"

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: core_app
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
