version: '3'
services:
  core_postgres:
    image: postgres:12.2-alpine
    container_name: core_postgres
    restart: unless-stopped
    ports:
      - 5432
    environment:
      POSTGRES_DB: 'mentorpaired_core'
      POSTGRES_PASSWORD: '@p@ssword'
    volumes:
      - postgres_db:/var/lib/postgresql

  core_app:
    depends_on:
      - core_postgres
    image: python:3.7
    container_name: core_app
    command: ./docker/scripts/start.sh
    ports:
      - 8000:8000
    env_file:
      - ./docker/app.local.env
    working_dir: /src
    volumes:
      - .:/src
      - core_deps:/root/.local

volumes:
  postgres_db:
  core_deps:


