version: "3"

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: coreuser
      POSTGRES_DB: coredb
      POSTGRES_PASSWORD: corepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: core_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
