# Generated by Django 3.0.7 on 2020-07-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_code', models.CharField(max_length=4096)),
                ('github_client_id', models.CharField(max_length=4096)),
                ('github_client_secret', models.CharField(max_length=4096)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
