# Generated by Django 3.0.3 on 2020-03-04 19:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='stacks',
        ),
        migrations.AddField(
            model_name='user',
            name='stacks',
            field=models.ManyToManyField(to='app.Stack'),
        ),
    ]
