# Generated by Django 3.0.3 on 2020-04-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200308_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferred_pronouns',
            new_name='pronouns',
        ),
        migrations.AlterField(
            model_name='request',
            name='interested_mentors',
            field=models.ManyToManyField(blank=True, related_name='prospective_mentor', to='app.InterestedMentor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='matched_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched', to='app.User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_name', to='app.User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='stack',
            field=models.ManyToManyField(related_name='tech_stacks', to='app.Stack'),
        ),
        migrations.AlterField(
            model_name='user',
            name='spoken_languages',
            field=models.ManyToManyField(related_name='speaks', to='app.SpokenLanguage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stacks',
            field=models.ManyToManyField(related_name='stacks', to='app.Stack'),
        ),
    ]
