# Generated by Django 3.0.7 on 2020-07-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_request_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Skill'),
        ),
        migrations.CreateModel(
            name='GithubAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=4096)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
