# Generated by Django 3.0.7 on 2020-07-09 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_githubauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubauth',
            old_name='github_client_id',
            new_name='github_access_token',
        ),
        migrations.RemoveField(
            model_name='githubauth',
            name='github_client_secret',
        ),
        migrations.RemoveField(
            model_name='githubauth',
            name='github_code',
        ),
        migrations.AddField(
            model_name='githubauth',
            name='github_user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
