# Generated by Django 3.0.7 on 2020-10-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201024_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(help_text='brief overview of what you would like to learn, your available days, etc', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=models.BooleanField(default=True, help_text='switch to false if you are not open to being matched'),
        ),
    ]
