# Generated by Django 3.0.7 on 2020-10-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_requestinterest_mentor'),
        ('app', '0003_auto_20201024_1236'),
    ]

    operations = [
    ]
