# Generated by Django 3.0.3 on 2020-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200410_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spoken_languages',
            field=models.ManyToManyField(related_name='languages', to='app.SpokenLanguage'),
        ),
    ]
