# Generated by Django 3.0.7 on 2020-07-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_request_skill'),
        ('app', '0003_auto_20200709_1522'),
    ]

    operations = [
    ]
