# Generated by Django 3.0.3 on 2020-04-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200410_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('NP', 'No Proficiency'), ('EP', 'Elementary Proficiency'), ('LWP', 'Limited Working Proficiency'), ('PWP', 'Professional Working Proficiency'), ('FWP', 'Full Working Proficiency'), ('NBP', 'Native Bilingual Proficiency')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun', models.CharField(choices=[('They', 'They/Them'), ('She', 'She/Her'), ('He', 'He/Him')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Introduce yourself to the request creator', max_length=500)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('WITHDRAWN', 'withdrawn')], default='OPEN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('MENTOR', 'mentor'), ('MENTEE', 'mentee')], default='MENTEE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='interested_mentors',
        ),
        migrations.RemoveField(
            model_name='request',
            name='matched_mentor',
        ),
        migrations.RemoveField(
            model_name='request',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pronouns',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stacks',
        ),
        migrations.AddField(
            model_name='request',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='app.User'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('HAS_INTERESTS', 'has_interests'), ('COMPLETED', 'completed'), ('CLOSED', 'closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(help_text="brief overview of what you'd                   like to learn, your available days, etc", max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='app.User'),
        ),
        migrations.DeleteModel(
            name='InterestedMentor',
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SkillProficiency'),
        ),
        migrations.AddField(
            model_name='requestinterest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Request'),
        ),
        migrations.AddField(
            model_name='user',
            name='pronoun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pronoun'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='roles', to='app.Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='app.Skill'),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LanguageProficiency'),
        ),
    ]
