# Generated by Django 3.0.3 on 2020-04-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200418_1329'),
    ]

    def delete_role(apps, schema_editor):
        Role = apps.get_model('app', 'Role')
        Role.objects.all().delete()

    def insert_pronoun(apps, schema_editor):
        Pronoun = apps.get_model('app', 'Pronoun')
        pronouns = ['They', 'She', 'He']
        for p in pronouns:
            pronoun = Pronoun(pronoun=p)
            pronoun.save()

    def insert_language_proficiency(apps, schema_editor):
        LanguageProficiency = apps.get_model('app', 'LanguageProficiency')
        proficiency_list = ['NP', 'EP', 'LWP', 'PWP', 'FWP', 'NBP']

        for prof in proficiency_list:
            proficiency = LanguageProficiency(level=prof)
            proficiency.save()

    def insert_skill_proficiency(apps, schema_editor):
        SkillProficiency = apps.get_model('app', 'SkillProficiency')
        proficiency_list = ['B', 'I', 'A']
        for prof in proficiency_list:
            proficiency = SkillProficiency(level=prof)
            proficiency.save()

    def insert_role(apps, schema_editor):
        Role = apps.get_model('app', 'Role')
        roles = ['ADMIN', 'MENTEE', 'MENTOR']
        for role in roles:
            role = Role(role=role)
            role.save()

    operations = [
        migrations.RunPython(delete_role),
        migrations.RunPython(insert_pronoun),
        migrations.RunPython(insert_language_proficiency),
        migrations.RunPython(insert_skill_proficiency),
        migrations.RunPython(insert_role)
    ]
