# Generated by Django 3.0.3 on 2020-04-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200420_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillproficiency',
            name='level',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=3),
        ),
    ]
