# Generated by Django 3.0.3 on 2020-04-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200420_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiency',
            name='level',
            field=models.CharField(choices=[('NP', 'No Proficiency'), ('EP', 'Elementary Proficiency'), ('LWP', 'Limited Working Proficiency'), ('PWP', 'Professional Working Proficiency'), ('FWP', 'Full Working Proficiency'), ('NBP', 'Native Bilingual Proficiency')], max_length=5, unique=True),
        ),
    ]
